import sys
import glob
import os.path

# import variables from other scons files
Import( '*' )

if not ( have_utdataflow and have_zmq):
	print "utDataflow, or zmq missing -- not building haptic utHapticIOComponents"	
	buildZMQ = False	
	Return('buildZMQ')

env = masterEnv.Clone()

# create component libraries

# automatically glob files from subdirectories
comp_sources = globSourceFiles( '*.cpp' )


# setup environment
env.AppendUnique( **mergeOptions(  utdataflow_all_options , zmq_options) )

# compile components as shared libraries
setupComponentBuild(env, comp_sources, 'zmq')

sources = globSourceFiles( '*.cpp' )
headers = globSourceFiles( '*.h' )
createVisualStudioProject(env, sources, headers, 'utZMQ')